name: Update Cached Data

on:
  schedule:
    - cron: "0 14 * * *" # Run daily at 14:00 UTC
  workflow_dispatch: # Allow manual trigger if needed

permissions:
  contents: write # Allow writing to the repository
  pages: write # Allow GitHub Pages deployment
  id-token: write # Allow OpenID Connect for GitHub Pages deployment

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify your Node.js version

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run the prefetching script to fetch Austrian and German prices
      - name: Fetch and Update Cached Data
        run: node prefetch.js

      # Deploy updated data to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Selected Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./page

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4